<a href="https://colab.research.google.com/github/systemcontroling/colab/blob/master/linear_regression%2C_Gradent_Descent_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

선형회귀는 간단히 말하면 실수의 값을 예측하는 것이다. 
예를 들으면 출산률 예측 등과 같은 문제를 회귀문제라고 한다.  

In [6]:
import tensorflow as tf

W = tf.Variable(tf.random_normal(shape=[1]))
b = tf.Variable(tf.random_normal(shape=[1]))
x = tf.placeholder(tf.float32)

linear_model = W*x+b

y = tf.placeholder(tf.float32)
loss =tf.reduce_mean(tf.square(linear_model - y))

optimizer = tf.train.GradientDescentOptimizer(0.01)
train_step = optimizer.minimize(loss)

x_train = [1, 2, 3, 4]
y_train = [2, 4, 6, 8]

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for i in range(100):
  sess.run(train_step, feed_dict = {x:x_train, y:y_train})

  x_test = [3.5 , 5, 10 , 7]

  print(sess.run(linear_model, feed_dict ={x: x_test}))

sess.close()

[-1.5483071 -1.6278915 -1.893173  -1.734004 ]
[-0.10209084  0.3824581   1.9976213   1.0285234 ]
[1.102543  2.0568624 5.2379274 3.3292885]
[2.1059399 3.4514265 7.9363823 5.245409 ]
[ 2.941708   4.6128864 10.183481   6.8411245]
[ 3.6378427  5.5801725 12.0546055  8.169945 ]
[ 4.217664   6.3857136 13.612546   9.276446 ]
[ 4.700596   7.0565224 14.90961   10.197757 ]
[ 5.1028214  7.615101  15.989367  10.964807 ]
[ 5.4378176  8.080193  16.88811   11.603359 ]
[ 5.7168136  8.467411  17.636072  12.134876 ]
[ 5.949161  8.789763 18.258438 12.577232]
[ 6.142651  9.058081 18.77618  12.945321]
[ 6.303773  9.28139  19.20678  13.251546]
[ 6.4379334  9.467208  19.564789  13.506241 ]
[ 6.5496345  9.621795  19.862331  13.71801  ]
[ 6.642627  9.75037  20.109512 13.894026]
[ 6.720036  9.857275 20.31474  14.04026 ]
[ 6.784464  9.946132 20.485023 14.161687]
[ 6.8380795 10.019953  20.6262    14.262451 ]
[ 6.882688 10.081253 20.743135 14.346005]
[ 6.9197946 10.132122  20.83988   14.415224 ]
[ 6.9506516 10.17430